"""empty message

Revision ID: 016a046dbd38
Revises: 
Create Date: 2023-06-12 19:36:35.581190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016a046dbd38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter', sa.String(length=30), nullable=True),
    sa.Column('fact', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact')
    # ### end Alembic commands ###
